/**
 * AI Party Game - Live Preview Trailer
 * Auto-plays a cinematic sample round with no backend dependency.
 */

import { showScreen, showToast } from './ui.js';

let SoundFX = null;

const state = {
    runId: 0,
    timers: new Set()
};

const PREVIEW_SCRIPT = {
    prompt: "Pitch your worst startup idea like it's about to raise $20M at YC Demo Day.",
    players: [
        {
            id: 'p1',
            answer: 'A smartwatch that rates your excuses in real time and sends them to HR.',
            votes: 1,
            scoreBase: 240,
            scoreGain: 75
        },
        {
            id: 'p2',
            answer: 'Uber, but for emotional support dragons with surge pricing on Mondays.',
            votes: 2,
            scoreBase: 315,
            scoreGain: 150
        },
        {
            id: 'p3',
            answer: 'AI breakup texts, auto-generated by legal interns and existential dread.',
            votes: 0,
            scoreBase: 280,
            scoreGain: 45
        }
    ],
    commentary: {
        intro: '🤖 AI Judge: "Loading chaos calibrations..."',
        responses: '🤖 AI Judge: "Creative instability detected. Excellent."',
        voting: '🤖 AI Judge: "Audience votes incoming. Brace for impact."',
        scoring: '🤖 AI Judge: "Winner selected. Deploying party fireworks."',
        finale: '🤖 AI Judge: "That was one round. Imagine five."'
    }
};

export function setSoundFX(soundFxRef) {
    SoundFX = soundFxRef;
}

function clearTimers() {
    state.timers.forEach((timer) => clearTimeout(timer));
    state.timers.clear();
}

function isActiveRun(runId) {
    return state.runId === runId;
}

function delay(ms, runId) {
    return new Promise((resolve) => {
        const timer = setTimeout(() => {
            state.timers.delete(timer);
            resolve(isActiveRun(runId));
        }, ms);
        state.timers.add(timer);
    });
}

function setTimelineStep(step) {
    document.querySelectorAll('.preview-step').forEach((item) => {
        item.classList.toggle('active', item.dataset.step === step);
    });
}

function setCommentary(text, live = false) {
    const el = document.getElementById('preview-ai-commentary');
    if (!el) return;
    el.textContent = text;
    el.classList.toggle('live', live);
}

function resetPreviewUI() {
    const prompt = document.getElementById('preview-prompt-text');
    if (prompt) prompt.textContent = 'Spinning up chaos...';

    PREVIEW_SCRIPT.players.forEach((player) => {
        const answerEl = document.getElementById(`preview-answer-${player.id}`);
        const votesEl = document.getElementById(`preview-votes-${player.id}`);
        const scoreEl = document.getElementById(`preview-score-${player.id}`);
        const card = document.getElementById(`preview-card-${player.id}`);

        if (answerEl) {
            answerEl.classList.remove('typing');
            answerEl.textContent = 'Waiting for answer...';
        }
        if (votesEl) votesEl.innerHTML = '';
        if (scoreEl) scoreEl.textContent = String(player.scoreBase);
        if (card) card.classList.remove('revealed', 'voted');
    });

    const confetti = document.getElementById('preview-confetti-layer');
    if (confetti) confetti.innerHTML = '';

    setTimelineStep('prompt');
    setCommentary(PREVIEW_SCRIPT.commentary.intro, false);
}

async function typeInto(el, text, runId, speed = 16) {
    if (!el) return false;
    el.textContent = '';
    el.classList.add('typing');

    for (let i = 0; i < text.length; i++) {
        if (!isActiveRun(runId)) return false;
        el.textContent += text[i];
        // eslint-disable-next-line no-await-in-loop
        const keepGoing = await delay(speed, runId);
        if (!keepGoing) return false;
    }

    el.classList.remove('typing');
    return true;
}

function addVotePips(playerId, count) {
    const container = document.getElementById(`preview-votes-${playerId}`);
    if (!container) return;

    container.innerHTML = '';
    for (let i = 0; i < count; i++) {
        const pip = document.createElement('span');
        pip.className = 'preview-vote-pip';
        pip.textContent = '❤️';
        container.appendChild(pip);
    }
}

async function animateScore(playerId, from, to, runId) {
    const el = document.getElementById(`preview-score-${playerId}`);
    if (!el) return false;
    const frames = 18;

    for (let i = 1; i <= frames; i++) {
        if (!isActiveRun(runId)) return false;
        const value = Math.round(from + ((to - from) * i) / frames);
        el.textContent = String(value);
        // eslint-disable-next-line no-await-in-loop
        const keepGoing = await delay(26, runId);
        if (!keepGoing) return false;
    }

    return true;
}

function launchConfettiBurst(targetId, amount = 56) {
    const layer = document.getElementById('preview-confetti-layer');
    const target = document.getElementById(targetId);
    if (!layer || !target) return;

    const rect = target.getBoundingClientRect();
    const originX = rect.left + rect.width / 2;
    const originY = rect.top + 16;
    const colors = ['#ff6b6b', '#4ecdc4', '#ffe66d', '#a66cff', '#ff9ff3', '#54a0ff'];

    for (let i = 0; i < amount; i++) {
        const bit = document.createElement('span');
        bit.className = 'preview-confetti-bit';
        bit.style.left = `${originX + (Math.random() - 0.5) * 120}px`;
        bit.style.top = `${originY + (Math.random() - 0.5) * 20}px`;
        bit.style.background = colors[Math.floor(Math.random() * colors.length)];
        bit.style.animationDuration = `${1 + Math.random() * 0.8}s`;
        bit.style.width = `${7 + Math.random() * 6}px`;
        bit.style.height = `${7 + Math.random() * 6}px`;
        layer.appendChild(bit);
        bit.addEventListener('animationend', () => bit.remove(), { once: true });
    }
}

async function runPreviewPlayback(runId) {
    const promptEl = document.getElementById('preview-prompt-text');
    if (!promptEl) return;

    setTimelineStep('prompt');
    if (!(await typeInto(promptEl, PREVIEW_SCRIPT.prompt, runId, 18))) return;
    if (SoundFX) SoundFX.play('roundStart');
    if (!(await delay(480, runId))) return;

    setTimelineStep('responses');
    setCommentary(PREVIEW_SCRIPT.commentary.responses, true);

    for (const player of PREVIEW_SCRIPT.players) {
        const card = document.getElementById(`preview-card-${player.id}`);
        const answerEl = document.getElementById(`preview-answer-${player.id}`);
        if (card) card.classList.add('revealed');
        // eslint-disable-next-line no-await-in-loop
        const done = await typeInto(answerEl, player.answer, runId, 12);
        if (!done) return;
        if (SoundFX) SoundFX.play('click');
        // eslint-disable-next-line no-await-in-loop
        if (!(await delay(250, runId))) return;
    }

    setTimelineStep('voting');
    setCommentary(PREVIEW_SCRIPT.commentary.voting, true);
    const voteOrder = ['p2', 'p1', 'p2'];

    for (const votedPlayerId of voteOrder) {
        const votedCard = document.getElementById(`preview-card-${votedPlayerId}`);
        if (votedCard) {
            votedCard.classList.add('voted');
        }
        const current = PREVIEW_SCRIPT.players.find((p) => p.id === votedPlayerId);
        if (current) {
            const visibleVotes = document.getElementById(`preview-votes-${votedPlayerId}`)?.children.length || 0;
            addVotePips(votedPlayerId, visibleVotes + 1);
        }
        if (SoundFX) SoundFX.play('vote');
        // eslint-disable-next-line no-await-in-loop
        if (!(await delay(420, runId))) return;
    }

    setTimelineStep('scoring');
    setCommentary(PREVIEW_SCRIPT.commentary.scoring, true);

    const ranking = [...PREVIEW_SCRIPT.players]
        .sort((a, b) => b.scoreGain - a.scoreGain);
    const winner = ranking[0];

    for (const player of PREVIEW_SCRIPT.players) {
        const from = player.scoreBase;
        const to = player.scoreBase + player.scoreGain;
        // eslint-disable-next-line no-await-in-loop
        const done = await animateScore(player.id, from, to, runId);
        if (!done) return;
    }

    launchConfettiBurst(`preview-card-${winner.id}`, 72);
    if (SoundFX) SoundFX.play('winner');
    if (!(await delay(600, runId))) return;

    setCommentary(`${PREVIEW_SCRIPT.commentary.finale} Winner: ${winner.id === 'p2' ? 'QuipQueen' : 'Party Legend'} 👑`, false);

    showToast('Preview complete. Ready to host your own round!', 'success');
}

function startPlayback() {
    state.runId += 1;
    clearTimers();
    resetPreviewUI();
    const run = state.runId;
    runPreviewPlayback(run);
}

export function showGamePreview() {
    showScreen('game-preview-screen');
    startPlayback();
}

export function replayGamePreview() {
    startPlayback();
}

export function exitGamePreview() {
    state.runId += 1;
    clearTimers();
    showScreen('welcome-screen');
}
